platform :ios, '11.0'
use_frameworks!

target 'AlertController_Example' do
  pod 'AMZAlertController', :path => '../'
#  pod 'AppmazoFoundation', :path => '../../AppmazoFoundation'
#  pod 'AppmazoUIKit', :path => '../../AppmazoUIKit'

#  target 'AlertController_Tests' do
#    inherit! :search_paths    
#  end
end
